import type { NextPage } from "next";
import Head from "next/head";
import { LazyImage } from "../components/Randomfox";
import { useState } from "react";
import type { MouseEventHandler } from "react";

const random = () => Math.floor(Math.random() * 123) + 1;

type ImageItem = { id: string; url: string };

const generateId = () => Math.random().toString(36).substr(2, 9);

const Home: NextPage = () => {
  const [images, setImages] = useState<ImageItem[]>([]);

  const addNewFox: MouseEventHandler = (event) => {
    event.preventDefault();
    const newImageItem: ImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${random()}.jpg`,
    };
    setImages([...images, newImageItem]);
  };

  return (
    <div>
      <Head>
        <title>React-ts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <button onClick={addNewFox}>Add fox</button>
        {images.map(({ id, url }) => (
          <div className="p-4" key={id}>
            {" "}
            <LazyImage
              src={url}
              onClick={() => {
                console.log("hola");
              }}
              title="Random Fox"
              width={320}
              height="auto"
              className="rounded bg-gray-300"
            />
          </div>
        ))}
      </main>
    </div>
  );
};

export default Home;
